export const LAB_REGISTER_REQUEST = "LAB_REGISTER_REQUEST";
export const LAB_REGISTER_FAILED = "LAB_REGISTER_FAILED";

export const LAB_LOADING = "LAB_LOADING";
export const SET_CURRENT_LAB = "SET_CURRENT_LAB";
export const LAB_LOGIN_FAILED = "LAB_LOGIN_FAILED";

export const LAB_APP_LIST_REQUEST = "LAB_APP_LIST_REQUEST";
export const LAB_APP_LIST_SUCCESS = "LAB_APP_LIST_SUCCESS";
export const LAB_APP_LIST_FAILED = "LAB_APP_LIST_FAILED";

// export const LAB_LIST_REQUEST = "LAB_LIST_REQUEST";
// export const LAB_LIST_SUCCESS = "LAB_LIST_SUCCESS";
// export const LAB_LIST_FAILED = "LAB_LIST_FAILED";