export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_APP_LIST_REQUEST = "USER_APP_LIST_REQUEST";
export const USER_APP_LIST_SUCCESS = "USER_APP_LIST_SUCCESS";
export const USER_APP_LIST_FAILED = "USER_APP_LIST_FAILED";